In [1]:
import pandas as pd

data = {
    "server": ["WEB01", "WEB02", "WEB03", "WEB04", "WEB05"],
    "status": ["Up", "Down", "Up", "Down", "Up"],
    "cpu": [35, 92, 45, 97, 88]
}

df = pd.DataFrame(data)

df.to_csv("servers.csv", index=False)

In [2]:
import os
print(os.listdir())

['Untitled.ipynb', 'early_wakeup_health_dataset.csv', '.ipynb_checkpoints', 'Pandas.ipynb', 'servers.csv']

In [3]:
df["cpu_warning"] = df["cpu"] > 90
print(df)

  server status  cpu  cpu_warning
0  WEB01     Up   35        False
1  WEB02   Down   92         True
2  WEB03     Up   45        False
3  WEB04   Down   97         True
4  WEB05     Up   88        False

In [4]:
df["cpu_status"] = "Normal"

In [5]:
df.loc[df["cpu"] > 90, "cpu_status"] = "Critical"

In [6]:
print(df)

  server status  cpu  cpu_warning cpu_status
0  WEB01     Up   35        False     Normal
1  WEB02   Down   92         True   Critical
2  WEB03     Up   45        False     Normal
3  WEB04   Down   97         True   Critical
4  WEB05     Up   88        False     Normal

In [7]:
df.sort_values("cpu")

  server status  cpu  cpu_warning cpu_status
0  WEB01     Up   35        False     Normal
2  WEB03     Up   45        False     Normal
4  WEB05     Up   88        False     Normal
1  WEB02   Down   92         True   Critical
3  WEB04   Down   97         True   Critical

In [8]:
df.sort_values("cpu", ascending=False)

  server status  cpu  cpu_warning cpu_status
3  WEB04   Down   97         True   Critical
1  WEB02   Down   92         True   Critical
4  WEB05     Up   88        False     Normal
2  WEB03     Up   45        False     Normal
0  WEB01     Up   35        False     Normal

In [9]:
top_servers = df.sort_values("cpu", ascending=False)
print(top_servers.head(3))

  server status  cpu  cpu_warning cpu_status
3  WEB04   Down   97         True   Critical
1  WEB02   Down   92         True   Critical
4  WEB05     Up   88        False     Normal