In [3]:
import pandas as pd

data = {
    "team": ["Web", "Web", "DB", "DB", "Web"],
    "status": ["Up", "Down", "Up", "Down", "Up"],
    "cpu": [35, 92, 45, 97, 88]
}

df = pd.DataFrame(data)

In [4]:
df.groupby("team")["cpu"].mean()

team
DB     71.000000
Web    71.666667
Name: cpu, dtype: float64

In [5]:
df.groupby("team")["cpu"].count()

team
DB     2
Web    3
Name: cpu, dtype: int64

In [6]:
df.groupby("team")["cpu"].max()

team
DB     97
Web    92
Name: cpu, dtype: int64

In [7]:
df.groupby("team")["cpu"].sum()

team
DB     142
Web    215
Name: cpu, dtype: int64

In [8]:
team_cpu = df.groupby("team")["cpu"].sum()
print(team_cpu)

team
DB     142
Web    215
Name: cpu, dtype: int64

In [9]:
print(df.groupby("team")["cpu"].sum())

team
DB     142
Web    215
Name: cpu, dtype: int64

In [10]:
# multiple calculations at once

df.groupby("team")["cpu"].agg(["count", "sum", "mean", "max"])

      count  sum       mean  max
team
DB        2  142  71.000000   97
Web       3  215  71.666667   92

In [13]:
import pandas as pd

data = {
    "team": ["Network", "Network", "Server", "Server", "Network"],
    "alerts": [15, 22, 8, 12, 18]
}

df = pd.DataFrame(data)

In [14]:
df.groupby("team")["alerts"].mean()

team
Network    18.333333
Server     10.000000
Name: alerts, dtype: float64

In [15]:
df.groupby("team")["alerts"].max()

team
Network    22
Server     12
Name: alerts, dtype: int64

In [16]:
df.groupby("team")["alerts"].sum()

team
Network    55
Server     20
Name: alerts, dtype: int64

In [18]:
df.groupby("team")["alerts"].agg(["count", "sum", "mean", "max"])

         count  sum       mean  max
team
Network      3   55  18.333333   22
Server       2   20  10.000000   12