# What is a DataFrame?
A DataFrame is a table, where the entire table becomes one object.

In [ ]:
# Reading a CSV File the Generic Way

# import csv

# with open("early_wakeup_health_dataset.csv") as file:
#    reader = csv.DictReader(file)

#    for row in reader:
#        print(row)

# Data Engineer Tip

Whenever working with a new dataset, get into the habit of running these commands first:  
df = pd.read_csv("enter csv.csv")  
print(df.head()) - shows the first 5 rows  
print(df.shape()) - shows the structure of the table   
print(df.columns) - shows all column names  
print(df.info()) - shows number of rows, columns, data types, and missing values

In [1]:
# Reading a CSV File with Pandas

import pandas as pd

df = pd.read_csv("early_wakeup_health_dataset.csv")
print(df)

     Person_ID  Age  Gender  Height_cm  Weight_kg    BMI    Country  \
0       P00001   76  Female      158.8       62.1  24.63      Italy
1       P00002   49  Female      160.9       68.5  26.45        USA
2       P00003   51  Female      151.9       54.8  23.77     Mexico
3       P00004   48    Male      167.6       81.3  28.93  Australia
4       P00005   68  Female      171.9       75.4  25.51        USA
...        ...  ...     ...        ...        ...    ...        ...
9995    P09996   66    Male      170.2       86.4  29.84    Nigeria
9996    P09997   70    Male      182.3       86.9  26.14     Canada
9997    P09998   29    Male      170.4       81.2  27.96      Italy
9998    P09999   22    Male      186.5       78.3  22.52      India
9999    P10000   58    Male      177.8       63.9  20.22     Brazil

             Occupation Marital_Status Wake_Up_Time  ... Obesity_Risk  \
0          Entrepreneur        Widowed        08:59  ...          Low
1            Freelancer         Single        06:35  ...       Medium
2                 Nurse         Single        07:31  ...          Low
3               Laborer         Single        08:36  ...       Medium
4     Software Engineer        Married        07:07  ...       Medium
...                 ...            ...          ...  ...          ...
9995            Teacher         Single        07:11  ...       Medium
9996            Athlete         Single        09:33  ...       Medium
9997             Lawyer        Married        07:58  ...       Medium
9998               Chef         Single        06:39  ...          Low
9999         Freelancer         Single        05:06  ...          Low

      Hypertension_Risk  Diabetes_Risk  Cardiovascular_Risk  \
0                  High         Medium               Medium
1                Medium         Medium                  Low
2                Medium         Medium                  Low
3                Medium            Low                  Low
4                  High         Medium               Medium
...                 ...            ...                  ...
9995               High           High               Medium
9996               High         Medium               Medium
9997                Low         Medium                  Low
9998             Medium         Medium                  Low
9999                Low            Low                  Low

      Sleep_Disorder_Risk  Health_Score  Fitness_Level  Healthy_Aging_Score  \
0                     Low          87.3      Excellent                 81.8
1                  Medium          72.0           Good                 75.2
2                     Low          75.2           Good                 77.1
3                  Medium          82.7      Excellent                 87.1
4                     Low          62.7        Average                 58.1
...                   ...           ...            ...                  ...
9995                  Low          67.8           Good                 53.8
9996                  Low          84.8      Excellent                 78.5
9997               Medium          54.2        Average                 59.2
9998               Medium          78.9           Good                 84.2
9999                  Low          88.7      Excellent                 90.4

      Wellness_Category Early_Waker
0             Excellent          No
1                  Good          No
2                  Good          No
3             Excellent          No
4               Average          No
...                 ...         ...
9995               Good          No
9996          Excellent          No
9997            Average          No
9998               Good          No
9999          Excellent         Yes

[10000 rows x 64 columns]

In [2]:
print(df.head())

  Person_ID  Age  Gender  Height_cm  Weight_kg    BMI    Country  \
0    P00001   76  Female      158.8       62.1  24.63      Italy
1    P00002   49  Female      160.9       68.5  26.45        USA
2    P00003   51  Female      151.9       54.8  23.77     Mexico
3    P00004   48    Male      167.6       81.3  28.93  Australia
4    P00005   68  Female      171.9       75.4  25.51        USA

          Occupation Marital_Status Wake_Up_Time  ... Obesity_Risk  \
0       Entrepreneur        Widowed        08:59  ...          Low
1         Freelancer         Single        06:35  ...       Medium
2              Nurse         Single        07:31  ...          Low
3            Laborer         Single        08:36  ...       Medium
4  Software Engineer        Married        07:07  ...       Medium

   Hypertension_Risk  Diabetes_Risk  Cardiovascular_Risk  Sleep_Disorder_Risk  \
0               High         Medium               Medium                  Low
1             Medium         Medium                  Low               Medium
2             Medium         Medium                  Low                  Low
3             Medium            Low                  Low               Medium
4               High         Medium               Medium                  Low

   Health_Score  Fitness_Level  Healthy_Aging_Score  Wellness_Category  \
0          87.3      Excellent                 81.8          Excellent
1          72.0           Good                 75.2               Good
2          75.2           Good                 77.1               Good
3          82.7      Excellent                 87.1          Excellent
4          62.7        Average                 58.1            Average

  Early_Waker
0          No
1          No
2          No
3          No
4          No

[5 rows x 64 columns]

In [3]:
print(df.shape)

(10000, 64)

In [4]:
print(df.columns)

Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early_Waker'],
      dtype='object')

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB
None

In [6]:
print(df.describe())
# a health check for numeric columns

              Age     Height_cm    Weight_kg           BMI  \
count  10000.0000  10000.000000  10000.00000  10000.000000
mean      44.6667    168.649160     73.10734     25.626963
std       17.5172      9.876706     16.29195      4.870317
min       18.0000    145.000000     33.60000     16.000000
25%       29.7500    161.400000     61.30000     22.170000
50%       43.0000    168.200000     72.00000     25.580000
75%       58.0000    175.500000     83.50000     28.862500
max       80.0000    205.500000    166.60000     44.560000

       Sleep_Duration_Hours  Sleep_Quality_Score  Number_of_Night_Awakenings  \
count          10000.000000         10000.000000                10000.000000
mean               7.229332             6.020190                    0.839100
std                1.118486             1.585689                    0.936215
min                4.000000             1.000000                    0.000000
25%                6.470000             4.900000                    0.000000
50%                7.230000             6.000000                    1.000000
75%                7.980000             7.100000                    1.000000
max               10.000000             9.800000                    6.000000

       Weekend_Sleep_Difference_Hours  Nap_Frequency_Per_Week  \
count                    10000.000000            10000.000000
mean                         1.027020                2.120800
std                          0.787941                1.905196
min                         -1.000000                0.000000
25%                          0.497500                0.750000
50%                          1.030000                2.000000
75%                          1.560000                3.000000
max                          3.810000                7.000000

       Screen_Time_Before_Bed_Hours  ...  Fatigue_Level_Score  \
count                  10000.000000  ...         10000.000000
mean                       1.144012  ...             3.124640
std                        1.044281  ...             1.705843
min                        0.000000  ...             1.000000
25%                        0.330000  ...             1.700000
50%                        0.810000  ...             2.900000
75%                        1.650000  ...             4.300000
max                        4.000000  ...            10.000000

       Immune_Health_Score    Mood_Score  Anxiety_Score  \
count          10000.00000  10000.000000   10000.000000
mean               6.56333      6.779650       5.133470
std                1.06034      1.255232       1.496242
min                2.60000      2.000000       1.000000
25%                5.90000      5.900000       4.100000
50%                6.60000      6.800000       5.100000
75%                7.30000      7.700000       6.200000
max               10.00000     10.000000      10.000000

       Depression_Risk_Score  Productivity_Score  Focus_Concentration_Score  \
count           10000.000000         10000.00000                10000.00000
mean                2.184520             7.06533                    6.85799
std                 1.286404             1.14750                    0.95254
min                 1.000000             2.80000                    3.50000
25%                 1.000000             6.30000                    6.20000
50%                 1.800000             7.00000                    6.90000
75%                 2.900000             7.90000                    7.50000
max                 8.800000            10.00000                   10.00000

       Life_Satisfaction_Score  Health_Score  Healthy_Aging_Score
count             10000.000000  10000.000000         10000.000000
mean                  7.416720     74.201360            74.812320
std                   1.147736     12.266227            14.627688
min                   2.900000     27.300000            12.400000
25%                   6.600000     66.000000            65.300000
50%                   7.400000     74.600000            75.700000
75%                   8.200000     82.800000            85.700000
max                  10.000000    100.000000           100.000000

[8 rows x 42 columns]

In [7]:
print(len(df))

10000

In [8]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Low,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No

In [9]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Sleep_Duration_Hours,Sleep_Quality_Score,Number_of_Night_Awakenings,Weekend_Sleep_Difference_Hours,Nap_Frequency_Per_Week,Screen_Time_Before_Bed_Hours,...,Fatigue_Level_Score,Immune_Health_Score,Mood_Score,Anxiety_Score,Depression_Risk_Score,Productivity_Score,Focus_Concentration_Score,Life_Satisfaction_Score,Health_Score,Healthy_Aging_Score
count,10000.0000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000
mean,44.6667,168.649160,73.10734,25.626963,7.229332,6.020190,0.839100,1.027020,2.120800,1.144012,...,3.124640,6.56333,6.779650,5.133470,2.184520,7.06533,6.85799,7.416720,74.201360,74.812320
std,17.5172,9.876706,16.29195,4.870317,1.118486,1.585689,0.936215,0.787941,1.905196,1.044281,...,1.705843,1.06034,1.255232,1.496242,1.286404,1.14750,0.95254,1.147736,12.266227,14.627688
min,18.0000,145.000000,33.60000,16.000000,4.000000,1.000000,0.000000,-1.000000,0.000000,0.000000,...,1.000000,2.60000,2.000000,1.000000,1.000000,2.80000,3.50000,2.900000,27.300000,12.400000
25%,29.7500,161.400000,61.30000,22.170000,6.470000,4.900000,0.000000,0.497500,0.750000,0.330000,...,1.700000,5.90000,5.900000,4.100000,1.000000,6.30000,6.20000,6.600000,66.000000,65.300000
50%,43.0000,168.200000,72.00000,25.580000,7.230000,6.000000,1.000000,1.030000,2.000000,0.810000,...,2.900000,6.60000,6.800000,5.100000,1.800000,7.00000,6.90000,7.400000,74.600000,75.700000
75%,58.0000,175.500000,83.50000,28.862500,7.980000,7.100000,1.000000,1.560000,3.000000,1.650000,...,4.300000,7.30000,7.700000,6.200000,2.900000,7.90000,7.50000,8.200000,82.800000,85.700000
max,80.0000,205.500000,166.60000,44.560000,10.000000,9.800000,6.000000,3.810000,7.000000,4.000000,...,10.000000,10.00000,10.000000,10.000000,8.800000,10.00000,10.00000,10.000000,100.000000,100.000000