After cleaning data, we often want to sort it

In [1]:
import pandas as pd

data = {
    "server": ["WEB01", "WEB02", "DB01", "WEB03"],
    "cpu_usage": [55, 92, 70, 45]
}

df = pd.DataFrame(data)

print(df.sort_values("cpu_usage"))

  server  cpu_usage
3  WEB03         45
0  WEB01         55
2   DB01         70
1  WEB02         92

In [2]:
# Descending Order

df.sort_values("cpu_usage", ascending=False)

  server  cpu_usage
1  WEB02         92
2   DB01         70
0  WEB01         55
3  WEB03         45

In [5]:
# Sorting by Multiple Columns

df.sort_values(
    ["server", "cpu_usage"],
    ascending=[True, False]
)

  server  cpu_usage
2   DB01         70
0  WEB01         55
1  WEB02         92
3  WEB03         45

In [7]:
import pandas as pd

data = {
    "server": ["WEB01", "WEB02", "WEB03", "DB01"],
    "memory_usage": [45, 88, 72, 95]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(
    "memory_usage",
    ascending=False
)

print(sorted_df)

  server  memory_usage
3   DB01            95
1  WEB02            88
2  WEB03            72
0  WEB01            45